# Generated by Django 5.1.1 on 2024-11-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('scrape', 'Scrape'), ('manual', 'Manual')], max_length=10)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('upload', 'Upload'), ('scrape', 'Scrape'), ('ai_processing', 'AI Processing'), ('validation', 'Validation')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('menu_item', 'Menu Item'), ('section', 'Section')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('spice_level', models.SmallIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietary_restrictions', models.ManyToManyField(to='menu.dietaryrestriction')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menusection')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStatistics',
            fields=[
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.restaurant')),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vegetarian_count', models.IntegerField(blank=True, null=True)),
                ('vegan_count', models.IntegerField(blank=True, null=True)),
                ('gluten_free_count', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='menu_restau_name_28c9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['cuisine_type'], name='menu_restau_cuisine_58694a_idx'),
        ),
        migrations.AddField(
            model_name='menuversion',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuversion'),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuversion'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['last_updated'], name='menu_search_last_up_8fc5e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchindex',
            unique_together={('entity_type', 'entity_id')},
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['section', 'display_order'], name='menu_menuit_section_36b4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='menu_menuit_name_138666_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price'], name='menu_menuit_price_7d229e_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available'], name='menu_menuit_is_avai_3a30d9_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['spice_level'], name='menu_menuit_spice_l_75d1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='menuversion',
            index=models.Index(fields=['effective_date'], name='menu_menuve_effecti_abebb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuversion',
            unique_together={('restaurant', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='menusection',
            index=models.Index(fields=['version', 'display_order'], name='menu_menuse_version_47bc51_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['version', 'status'], name='menu_proces_version_102fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['start_time'], name='menu_proces_start_t_745635_idx'),
        ),
    ]
