# Generated by Django 5.1.1 on 2024-11-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_is_avai_3a30d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_menuit_spice_l_75d1a6_idx',
        ),
    ]
