# Generated by Django 5.1.1 on 2024-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_menu_menuit_is_avai_3a30d9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
