# Generated by Django 5.1.1 on 2024-12-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_restaurant_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menustatistics',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='processinglog',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
